x-common: &common
  restart: always
  logging:
    options:
      max-size: "10m"
      max-file: "5"

services:

  sing-box:
    <<: *common
    image: ghcr.io/sagernet/sing-box:v1.13.19
    container_name: sing-box
    ports:
      - "443:443/udp"
      - "443:443/tcp"
    volumes:
      - ./sing-box/config:/etc/sing-box
      - ./sing-box/data:/var/lib/sing-box
      - /etc/letsencrypt:/etc/letsencrypt:ro
    command: -D /var/lib/sing-box -C /etc/sing-box run
